FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine@sha256:b02b08b6ae0c2054a856ba5f3c0db38bbe0971c433f059b962dc8173493b9053 as build

# renovate: depName=https://github.com/microsoft/wopi-validator-core depBranch=main
ENV WOPI_VALIDATOR_VERSION="${WOPI_VALIDATOR_VERSION:-4c995a0d8c32ed5f55cac1dd3209d2450e12725c}"

WORKDIR /
ADD https://github.com/microsoft/wopi-validator-core/archive/$WOPI_VALIDATOR_VERSION.tar.gz /wopi-validator-core.tar.gz
RUN tar xvfz wopi-validator-core.tar.gz --directory /
RUN mv /wopi-validator-core-$WOPI_VALIDATOR_VERSION /app

WORKDIR /app/
RUN dotnet build -c Release
RUN find /app/src/WopiValidator/bin/Release

FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine@sha256:edab48ed5156a26eaded81520003ff4d02b4978192c0b9ead8ab4f5491e5d6d5

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wopi-validator"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wopi-validator"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wopi-validator"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wopi-validator"

WORKDIR /app/
COPY --from=build /app/LICENSE /app/LICENSE
COPY --from=build /app/src/WopiValidator/bin/Release/net6.0 /app

ENTRYPOINT [ "/app/Microsoft.Office.WopiValidator"]
