FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine@sha256:4de9841e3d76e88d56881a0273054af9a13ca1788624dde6e45eaa211c7005e2 as build

# renovate: depName=https://github.com/microsoft/wopi-validator-core depBranch=main
ENV WOPI_VALIDATOR_VERSION="${WOPI_VALIDATOR_VERSION:-4c995a0d8c32ed5f55cac1dd3209d2450e12725c}"

WORKDIR /
ADD https://github.com/microsoft/wopi-validator-core/archive/$WOPI_VALIDATOR_VERSION.tar.gz /wopi-validator-core.tar.gz
RUN tar xvfz wopi-validator-core.tar.gz --directory /
RUN mv /wopi-validator-core-$WOPI_VALIDATOR_VERSION /app

WORKDIR /app/
RUN dotnet build -c Release
RUN find /app/src/WopiValidator/bin/Release

FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine@sha256:19d2cc3db7d1a6ce55fa9a1434054ea9b7812435f51b46a7cf010a217d040d1a

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI wopi-validator"
LABEL org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/wopi-validator"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/wopi-validator"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/wopi-validator"

WORKDIR /app/
COPY --from=build /app/LICENSE /app/LICENSE
COPY --from=build /app/src/WopiValidator/bin/Release/net6.0 /app

ENTRYPOINT [ "/app/Microsoft.Office.WopiValidator"]
